kind: pipeline
type: docker
name: default

steps:
  - name: test and coverage report
    image: node:15.12.0-alpine
    environment:
      DB_URL: postgres://postgres:postgres@postgres/intres-messenger
      REDIS_URL: redis://redis/1
      PORT: 3000
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
      JWT_SECRET:
        from_secret: JWT_SECRET
    commands:
      - yarn install
      - yarn test --coverage
      - apk -U add git curl bash findutils
      - bash -c '/bin/bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage-final.json'

services:
  - name: postgres
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intres-messenger

  - name: redis
    image: redis:6.2.1-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD: yes
