version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file: production.env
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intres-messenger
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.1-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
